kafkaConnect:
  name: "kafka-connect-cluster"
  version: "3.5.1"
  replicas: 1
  config:
    topics: random-messages

kafka:
  name: "kafka-cluster"
  version: "3.5.1"
  replicas: 3
  cluster:
    # For upgrading details see
    # https://strimzi.io/docs/operators/latest/deploying.html#proc-upgrading-brokers-newer-kafka-str
    logMessageFormatVersion: "3.2.1"
    interBrokerProtocolVersion: "3.2.1"
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinInSyncReplicas: 1
    autoCreateTopicsEnable: true
    defaultReplicationFactor: 3
    minInsyncReplicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi

nodeAffinityLabel: kubernetes.io/hostname

zookeeper:
  replicas: 3
  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi

entityOperator:
  topicOperator:
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 20m
        memory: 224Mi
  userOperator:
    resources:
      limits:
        cpu: 400m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 192Mi
  tlsSidecar:
    resources:
      limits:
        cpu: 600m
        memory: 16Mi
      requests:
        cpu: 10m
        memory: 8Mi

kafkaConsumer:
  name: "kafka-consumer"
  image:
    repository: ghcr.io/sheveg/kafkaconsumer
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main"
  env:
  - name: Kafka__BootstrapUrl
    value: "kafka-cluster-kafka-bootstrap:9092"
  - name: Kafka__Topic
    value: "random-messages"
  replicaCount: 1

kafkaProducer:
  name: "kafka-producer"
  image:
    repository: ghcr.io/sheveg/kafkaproducer
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main"
  env:
  - name: Kafka__BootstrapUrl
    value: "kafka-cluster-kafka-bootstrap:9092"
  - name: Kafka__Topic
    value: "random-messages"
  replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
   fsGroup: 15555

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 15555
  runAsGroup: 15555
  privileged: false
  allowPrivilegeEscalation: false