{{- if .Capabilities.APIVersions.Has "kafka.strimzi.io/v1beta2" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
spec:
  kafka:
    version: {{ .Values.cluster.version }}
    replicas: {{ .Values.cluster.replicas }}
    listeners:
      - name: {{ .Values.cluster.listener.name }}
        port: {{ .Values.cluster.listener.port }}
        type: {{ .Values.cluster.listener.type }}
        tls: {{ .Values.cluster.listener.tls }}
        authentication:
          type: {{ .Values.cluster.listener.authentication.type }}
      - name: external
        port: 9094
        type: nodeport
        tls: false
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: {{ .Values.cluster.config.offsetsTopicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.cluster.config.transactionStateLogReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.cluster.config.transactionStateLogMinInSyncReplicas }}
      log.message.format.version: {{ .Values.cluster.config.logMessageFormatVersion | quote }}
      inter.broker.protocol.version: {{ .Values.cluster.config.interBrokerProtocolVersion | quote }}
      auto.create.topics.enable: {{ .Values.cluster.config.autoCreateTopicsEnable | quote }}
      default.replication.factor: {{ .Values.cluster.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.cluster.config.minInsyncReplicas }}
    rack:
      topologyKey: {{ .Values.nodeAffinityLabel }}
    storage:
      type: jbod
      volumes:
      - class: standard
        deleteClaim: false
        id: 0
        size: 1Gi
        type: persistent-claim
    template:
      clusterRoleBinding:
        metadata:
          annotations:
            argocd.argoproj.io/sync-options: Prune=false
            argocd.argoproj.io/compare-options: IgnoreExtraneous
    resources:
      {{- toYaml .Values.cluster.resources | nindent 6 }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      class: standard
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .Values.nodeAffinityLabel }}
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: kafka
                    strimzi.io/name: kafka-zookeeper
                topologyKey: {{ .Values.nodeAffinityLabel }}
              weight: 100
    resources:
      {{- toYaml .Values.zookeeper.resources | nindent 6 }}
  entityOperator:
    topicOperator:
      resources:
        {{- toYaml .Values.entityOperator.topicOperator.resources | nindent 8 }}
    userOperator:
      resources:
        {{- toYaml .Values.entityOperator.userOperator.resources | nindent 8 }}
    tlsSidecar:
      resources:
        {{- toYaml .Values.entityOperator.tlsSidecar.resources | nindent 8 }}
{{- end }}
