{{- if .Capabilities.APIVersions.Has "kafka.strimzi.io/v1beta2" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: connectCluster
metadata:
  name: {{ .Values.connectCluster.name }}
  annotations:
  # use-connector-resources configures this connectCluster
  # to use connectClusteror resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: {{ .Values.connectCluster.version }}
  replicas: {{ .Values.connectCluster.replicas }}
  bootstrapServers: {{ .Values.cluster.name }}-kafka-bootstrap:9092
  build:
    output:
      type: {{ .Values.connectCluster.build.output.type }}
      image: {{ .Values.connectCluster.build.output.image }}
      pushSecret: {{ .Values.connectCluster.build.registrySecret }}
    plugins:
      {{- toYaml .Values.connectCluster.build.plugins | nindent 6 }}
  template:
    pod:
      imagePullSecrets:
        - name: {{ .Values.connectCluster.build.registrySecret }}
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
{{- end }}