{{- if .Capabilities.APIVersions.Has "kafka.strimzi.io/v1beta2" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.name }}
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: {{ .Values.kafkaConnect.config.topics }}
    value.converter.schemas.enable: false
    auto.create: true
    connection.url: jdbc:postgresql://postgresql-cluster.postgres.svc:5432/logs
    connection.user: loguser
    connection.password: postgrespw
{{- end }}