{{- if .Capabilities.APIVersions.Has "kafka.strimzi.io/v1beta2" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.name }}
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: {{ .Values.kafkaConnect.config.topics }}
    value.converter.schemas.enable: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    key.converter: org.apache.kafka.connect.json.JsonConverter
    auto.create: true
    auto.evolve: true
    pk.mode: record_value
    pk.fields: id
    insert.mode : upsert
    connection.url: jdbc:postgresql://postgresql-cluster.postgres.svc:5432/logs
    connection.user: loguser
    connection.password: postgrespw
{{- end }}