{{- if .Capabilities.APIVersions.Has "kafka.strimzi.io/v1beta2" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name:  {{ .Values.producer.user }}
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ .Values.topic }}
          patternType: literal
        operation: Write
        type: allow
{{- end }}